In [1]:
import numpy as np

In [9]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a*b)

[5 7 9]
[ 4 10 18]


In [10]:
c=np.array([1,2,3])
d=np.array([2])
print(c*d)
print(c+d)

[2 4 6]
[3 4 5]


In [11]:
e=np.array([1,2,"ok"])
print(e)

['1' '2' 'ok']


In [12]:
e=np.array([1,2,4.0])
print(e)

[1. 2. 4.]


In [1]:
print("Trying ctrl enter to run cell")

Trying ctrl enter to run cell


In [4]:
print("Trying shift enter to run cell and add new cell")

Trying shift enter to run cell and add new cell
