In [1]:
import numpy as np

In [3]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
# these both add as new row
print(np.concatenate([a,b],axis=0))# add in the same axis 
print(np.vstack([a,b]))

#these both add a new column 
print(np.concatenate([a,b],axis=1))# nest new one into axis of other
print(np.hstack([a,b]))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [14]:
#x=np.array([[1,2],[3,4]])
#y=np.array([[5,6,7],[7,8,9]])

#print(np.concatenate([x,y],axis=0))
#print(np.vstack([x,y]))


#print(np.concatenate([x,y],axis=1))
#print(np.hstack([x,y]))
print(x.shape)
print(y.shape)
#Wrong because shape of both x and y are different

(2, 2)
(2, 3)


In [ ]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6,7],[7,8,9]])

In [4]:
c=np.array([1,2,3,4,5,6])
print(np.array_split(c,2))
print(np.array_split(c,3))
print(np.array_split(c,4))
print(np.array_split(c,5))
print(np.array_split(c,6))
print(np.array_split(c,7))

[array([1, 2, 3]), array([4, 5, 6])]
[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
[array([1, 2]), array([3]), array([4]), array([5]), array([6])]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int64)]


In [9]:
c=np.array([[1,2,3],[4,5,6]])
print(np.array_split(c,2))
print(np.array_split(c,3))
print(np.array_split(c,4))
print(np.array_split(c,5))
print(np.array_split(c,6))
print(np.array_split(c,7))

[array([[1, 2, 3]]), array([[4, 5, 6]])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int64)]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int64), array([], shape=(0, 3), dtype=int64)]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int64), array([], shape=(0, 3), dtype=int64), array([], shape=(0, 3), dtype=int64)]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int64), array([], shape=(0, 3), dtype=int64), array([], shape=(0, 3), dtype=int64), array([], shape=(0, 3), dtype=int64)]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int64), array([], shape=(0, 3), dtype=int64), array([], shape=(0, 3), dtype=int64), array([], shape=(0, 3), dtype=int64), array([], shape=(0, 3), dtype=int64)]
