In [2]:
import numpy as np

In [10]:
a=np.array([1,2,3,4])

print(np.append(a,7))# add at end 
print(a)

print(np.append(a,[7,8,9]))# add all and end sequentially as given
print(a)

print(np.insert(a,1,7))#insert at position
print(np.insert(a,1,[7,8,9]))#insert at position sequentially as given
#print(np.insert(a,[1,0],[7,8,9]))
print(a)

[1 2 3 4 7]
[1 2 3 4]
[1 2 3 4 7 8 9]
[1 2 3 4]
[1 7 2 3 4]
[1 7 8 9 2 3 4]
[1 2 3 4]


In [24]:
b=np.array([[1,2],[3,4]])
print(np.append(b,[7,8,9]))# add all and end sequentially as given but make as 1D array
print(np.append(b,[7]))# add at end but make as 1D array
#print(np.append(b,[7,8],axis=0))
#print(np.append(b,[7,8],axis=1))
#print(np.append(b,[7],axis=0))
print(b)
print(np.insert(b,1,[7,8]))# add all at position sequentially as given but make as 1D array
print(np.insert(b,1,[7,8],axis=0))# add at given position as new row but keep it as 2D array
print()
print(np.insert(b,[1,3],[7]))
print(np.insert(b,[1,3],[7,8]))#add at multiiple positions but by matching and as 1D array
print(np.insert(b,1,[7,8],axis=1))#add at given position as new column for each item and keep it as 2D Array
print(np.insert(b,[1,2],[7,8],axis=0))# add at given positions as new row but keep it as 2D array
print(np.insert(b,[1,2],[7,8],axis=1))

[1 2 3 4 7 8 9]
[1 2 3 4 7]
[[1 2]
 [3 4]]
[1 7 8 2 3 4]
[[1 2]
 [7 8]
 [3 4]]

[1 7 2 3 7 4]
[1 7 2 3 8 4]
[[1 7 2]
 [3 8 4]]
[[1 2]
 [7 8]
 [3 4]
 [7 8]]
[[1 7 2 8]
 [3 7 4 8]]


In [25]:
#print(np.insert(b,1,[[7,8],[9,10]]))
#print(np.insert(b,1,[[7,8],[9,10]],axis=0))
#print(np.insert(b,1,[[7,8],[9,10]],axis=1))



In [27]:
f=np.array([[20,30,40],[50,60,70]])
print(np.delete(f,5))
print(np.delete(f,1,axis=0))
print(np.delete(f,1,axis=1))

[20 30 40 50 60]
[[20 30 40]]
[[20 40]
 [50 70]]
