In [3]:
import numpy as np

In [10]:
a=np.array([10,20,30,40])
print(a[0:3])
print(a[2:])
print(a[::-1])
b=a[:]
print(b)

[10 20 30]
[30 40]
[40 30 20 10]
[10 20 30 40]


In [22]:
b=np.array([[10,20,30,40],[50,60,70,80]])
print(b[0:2,1:])#possible for 2D Array with 2 rows

[[20 30 40]
 [60 70 80]]


In [25]:
b=np.array([[10,20,30,40],[50,60,70,80]])
print(b[0,1:])#possible for 2D array with any number of rows-> from 0th row show array from 1st index till end 
print(b[0,::-1])#reversing also possible
print(c[0,2])#possible for 2D array with any number of rows->from 0th row show only one element present at 2nd index

[20 30 40]
[40 30 20 10]


In [6]:
c=np.array([[10,20,30,40],[50,60,70,80],[20,40,50,30]])
print(c[2,1:])
#print(c[0:2,0:2,0:2]) Not possible for 2D Array with 3 rows 

[40 50 30]
