In [1]:
import numpy as np

In [13]:
a=[[1,2,3,10],[4,5,6,11],[7,8,9,12]]
b=np.array(a)

In [14]:
print(b)
b.shape

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


(3, 4)

In [16]:
len(b)

3

In [18]:
b.size

12

In [19]:
b.ndim

2

In [20]:
b.dtype

dtype('int64')

In [24]:
print(b.astype(float))#take this as new ndarray
print(b)

[[ 1.  2.  3. 10.]
 [ 4.  5.  6. 11.]
 [ 7.  8.  9. 12.]]
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]
