In [3]:
import numpy as np

In [15]:
a=np.array([1,2,4,6,7,8])
b=np.array([2,3,4,4,5,8])
c=np.array([[1,2],[4,6],[7,8]])
d=np.array([[2,3],[4,4],[5,8]])

print(np.max(a))
print(np.min(a))
print(np.size(a))
print(np.sum(a))
print()
print(np.max(c))
print(np.min(c))
print(np.size(c))
print(np.sum(c))

8
1
6
28

8
1
6
28


In [16]:
print(np.cumsum(a))
print(np.cumprod(a))
print()
print(np.cumsum(c))
print(np.cumprod(c))

[ 1  3  7 13 20 28]
[   1    2    8   48  336 2688]

[ 1  3  7 13 20 28]
[   1    2    8   48  336 2688]


In [12]:
print(np.sum(np.cumsum([a,b],axis=0)))
print(np.cumsum([a,b],axis=0))
print(np.cumprod([a,b],axis=0))

82
[[ 1  2  4  6  7  8]
 [ 3  5  8 10 12 16]]
[[ 1  2  4  6  7  8]
 [ 2  6 16 24 35 64]]
