In [1]:
import numpy as np 

In [2]:
a=np.array([[3,9],[27,81]])
b=np.array([[2,4],[8,16]])
c=np.array([3])
d=np.array([2])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)


[[ 5 13]
 [35 97]]
[[ 1  5]
 [19 65]]
[[   6   36]
 [ 216 1296]]
[[1.5    2.25  ]
 [3.375  5.0625]]
[[1 2]
 [3 5]]
[[1 1]
 [3 1]]


In [3]:
print(a+c)
print(a-c)
print(a*c)
print(a/c)
print(a//c)
print(a%c)

[[ 6 12]
 [30 84]]
[[ 0  6]
 [24 78]]
[[  9  27]
 [ 81 243]]
[[ 1.  3.]
 [ 9. 27.]]
[[ 1  3]
 [ 9 27]]
[[0 0]
 [0 0]]


In [7]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[ 5 13]
 [35 97]]
[[ 1  5]
 [19 65]]
[[   6   36]
 [ 216 1296]]
[[1.5    2.25  ]
 [3.375  5.0625]]


In [8]:
print(np.pow(a,c))
print(np.sqrt(a))

[[    27    729]
 [ 19683 531441]]
[[1.73205081 3.        ]
 [5.19615242 9.        ]]


In [9]:
print(np.pow(a,b))

[[                  9                6561]
 [       282429536481 8733086111712066817]]
