In [1]:
import numpy as np 

In [3]:
a=np.array([1,2,7,4,8,9])
b=np.array([[1,9,2],[7,4,8]])
print(np.sort(a))
print(np.sort(b))

[1 2 4 7 8 9]
[[1 2 9]
 [4 7 8]]


In [7]:
a=np.sort(a)
print(a)
print(np.searchsorted(a,4))#works on sorted array if not sorted first sort array then tell element's index

print(np.where(a==4))# check elements for condition and return list of index of all the elements that satisfy that condition
print(np.where(a%2==0))

[1 2 4 7 8 9]
2
(array([2]),)
(array([1, 2, 4]),)


In [12]:
print(np.where(b==7))
print(np.where(b%2==0))# in 2D array with get 2 list and to find position of element we see b[i index in 1st list][i index in 2nd list]

(array([1]), array([0]))
(array([0, 1, 1]), array([2, 1, 2]))


In [15]:
#Now to print one of the elements that is divisile by 2 from given two list that were returned 
print(b[0,2])
print(b[1,1])
print(b[1,2])

2
4
8


In [16]:
g=np.array([3,4,5,7,8,10])
print(g[[True,False,True,True,False,False]])
print(g[g%2 != 0])

[3 5 7]
[3 5 7]


In [17]:
g=np.array([[3,4,5],[7,8,10]])
print(g[[[True,False,True],[True,False,False]]])
print(g[g%2 != 0])

[3 5 7]
[3 5 7]
